FROM node:22

ARG VITE_SERVER_URL=http://127.0.0.1:5000
ENV VITE_SERVER_URL=$VITE_SERVER_URL

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 4173
CMD ["npm", "run", "preview", "--", "--host"]
